server:
  port: 5080
  forward-headers-strategy: framework

spring:
  profiles:
    default: dev   # 아무것도 지정하지 않으면 자동으로 dev

  cloud:
    aws:
      region:
        static: ap-northeast-2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          cognito:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile

---
spring:
  config:
    import: "aws-parameterstore:/tech-gather/dev/cognito/"
  config.activate.on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/techgather?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    import: "aws-parameterstore:/tech-gather/prod/cognito/"
  config.activate.on-profile: prod

