target:
  entries:
    woowahan:
      url: https://www.woowahan.com
      adapter:
        fetcher: httpFetcher
        crawler: htmlCrawler
        extractor: defaultExtractor
    toss:
      url: https://toss.im
      adapter:
        fetcher: httpFetcher
        crawler: htmlCrawler
        extractor: defaultExtractor